name: go test

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: aqua-verifier-go

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Checkout micro-PKC
      uses: actions/checkout@v2
      with:
        repository: inblockio/micro-PKC
        path: micro-PKC

    - name: Run micro-PKC
      run: |
        cd micro-PKC && ./pkc setup --wallet-address 0x02F40398247BF79eBb995Bf5AE6f635dD0BCE81a

    - name: Build
      run: cd aqua-verifier-go && go build -v ./...

    - name: Test
      run: cd aqua-verifier-go && go test -v -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Codecov
      uses: codecov/codecov-action@v2
      with:
        #root_dir: /home/runner/work/aqua-verifier-go/aqua-verifier-go/aqua-verifier-go
        working-directory: /home/runner/work/aqua-verifier-go/aqua-verifier-go/aqua-verifier-go
